#!/bin/bash

set -e

docker_repos=(
  docker.io/quiexotic/dokuwiki-fcgi
  ghcr.io/hellyna/dokuwiki-fcgi
)

for repo in "${docker_repos[@]}"; do
  docker build --quiet --pull -t "$repo" .

  case $1 in
    push)
      docker push --quiet "$repo"
      ;;
  esac
done
